python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --use_layer_norm --dropout 0.1 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --use_layer_norm --dropout 0.2 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --use_layer_norm --dropout 0.3 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --use_layer_norm --dropout 0.4 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --use_layer_norm --dropout 0.5 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --use_layer_norm --dropout 0.6 --batch_size 16 --group_name tuning_ver1


python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --dropout 0.1 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --dropout 0.2 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --dropout 0.3 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --dropout 0.4 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --dropout 0.5 --batch_size 16 --group_name tuning_ver1
python main.py --in_channel 13 --adding_type 0 --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24h --validate_every 3000 --dropout 0.6 --batch_size 16 --group_name tuning_ver1
