CUDA_VISIBLE_DEVICES=1 python main.py --cfg config/default.yaml  \
        --name strans \
        --in_channel 13 \
        --adding_type 0 \
        --dropout 0.3 \
        --height 13 \
        --width 23 \
        --data_idx_dir /mnt/disk1/tunn/Subseasonal_Prediction/data6789_reg_3_seed52 \
        --gauge_data_path /mnt/disk1/env_data/Gauge_thay_Tan/Final_Data_Region_3.csv \
        --npyarr_dir /mnt/disk1/env_data/S2S_0.125/nparr_reg_3/Step24h \
        --processed_ecmwf_dir /mnt/disk1/env_data/S2S_0.125/reg_3 \
        --lat_start 21.5 \
        --lon_start 105 \
        --use_layer_norm \
        --loss_func mse \
        --lr 5e-4 \
        --use_lrscheduler \
        --scheduler_type ReduceLROnPlateau \
        --plateau_patience 3 \
        --plateau_min_lr 1e-6 \
        --plateau_factor 0.5 --plateau_verbose \
        --group_name region3 \
        --batch_size 32