python main.py --in_channel 13 --adding_type 0  --group_name tuning_ver1 --processed_ecmwf_dir /home/user01/aiotlab/longnd/subseasonal --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24 --use_layer_norm --dropout 0.3 --batch_size 1 --loss_func weightedmse

python main.py --in_channel 13 --adding_type 0  --group_name tuning_ver1 --processed_ecmwf_dir /home/user01/aiotlab/longnd/subseasonal --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24 --use_layer_norm --dropout 0.3 --batch_size 1 --loss_func expweightedloss --k 0.1
python main.py --in_channel 13 --adding_type 0  --group_name tuning_ver1 --processed_ecmwf_dir /home/user01/aiotlab/longnd/subseasonal --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24 --use_layer_norm --dropout 0.3 --batch_size 1 --loss_func expweightedloss --k 0.2
python main.py --in_channel 13 --adding_type 0  --group_name tuning_ver1 --processed_ecmwf_dir /home/user01/aiotlab/longnd/subseasonal --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24 --use_layer_norm --dropout 0.3 --batch_size 1 --loss_func expweightedloss --k 0.5
python main.py --in_channel 13 --adding_type 0  --group_name tuning_ver1 --processed_ecmwf_dir /home/user01/aiotlab/longnd/subseasonal --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24 --use_layer_norm --dropout 0.3 --batch_size 1 --loss_func expweightedloss --k 1
python main.py --in_channel 13 --adding_type 0  --group_name tuning_ver1 --processed_ecmwf_dir /home/user01/aiotlab/longnd/subseasonal --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24 --use_layer_norm --dropout 0.3 --batch_size 1 --loss_func expweightedloss --k 2
python main.py --in_channel 13 --adding_type 0  --group_name tuning_ver1 --processed_ecmwf_dir /home/user01/aiotlab/longnd/subseasonal --data_dir /home/user01/aiotlab/longnd/subseasonal --data_idx_dir data789_seed52 --npyarr_dir /home/user01/aiotlab/longnd/subseasonal/Step24 --use_layer_norm --dropout 0.3 --batch_size 1 --loss_func expweightedloss --k 5

